### ISSUE TITLE
Etude : Set all users as admin in new DM

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-backend#19]
Lors de la creation des DM, les 2 utilisateurs ne sont pas admins.

L'idee de ce ticket est d'analyse quelle serait le changement/solution a effectuer pour corriger ce comportement.

Une piste serait d'etudier le module suivant :
https://github.com/element-hq/synapse-room-access-rules/blob/main/room_access_rules/__init__.py

**Comment by mcalinghee** [comment]
### Analysis
- par defaut, Synapse cree une DM [en attribuant les droits admins aux invitees (a l'autre interlocuteur) ](https://github.com/element-hq/synapse/blob/c925b4556798539d172664ed69734c8611f669d2/synapse/handlers/room.py#L1214)
- Cependant, ce module [synapse-room-access-rules](https://github.com/element-hq/synapse-room-access-rules/blob/08e019173909b9c14c0bd92a0af8e49e858f4ae3/room_access_rules/__init__.py#L253) change les permissions juste avant la creation de la room, et enlève donc les droits admins des invitees par [remplacement](https://github.com/element-hq/synapse/blob/0529c9fd9a9c0cd41eefeeba4b274ef590594e50/synapse/handlers/room.py#L1207-L1207).

**Comment by odelcroi** [comment]
- [ ] Créer le ticket pour l'implementation
