### ISSUE TITLE
Forbid encryption of public rooms

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-backend#21]
## Why
enable encryption on large public rooms can have dramatic side effects

## What
Modify backend module to Forbid encryption of public rooms

```[tasklist]
### Tasks
- [ ] https://github.com/tchapgouv/synapse-room-access-rules/pull/1
- [ ] https://github.com/tchapgouv/tchap-infra/pull/2524
```

**Comment by MatMaul** [comment]
https://github.com/tchapgouv/synapse-room-access-rules/pull/1
