### ISSUE TITLE
Upgrade Synapse 1.103 - Tchap Annonces

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-backend#29]
### Tests
Pour lancer les tchap annonce, il faut utiliser cette commande coté infra
exemple : https://github.com/tchapgouv/tchap-infra/pull/2324
NB : Renseigner un token valid pour le fake vault de la dev vault_matrix_synapse_admin_access_token

```ANSIBLE_LIBRARY=$PWD/library ansible-playbook tasks/server_notice.yml -D -l matrix.dev01.tchap.incubateur.net -e "server_notice=****" ```

Pour voir les logs 
```
ssh matrix.dev01.tchap.incubateur.net
sudo tail -f -n 1000000  /mnt/logs/synapse/matrix-synapse.log | grep  "Creating server notices room for"
```

### Results 
![image](https://github.com/tchapgouv/tchap-infra/assets/4077729/74d48f77-4d12-41e4-a12b-b231ee8da67e)

Le petit bouclier rouge c'est :

![image](https://github.com/tchapgouv/tchap-infra/assets/4077729/729d4b47-766f-4ec0-8536-34febf5fe573)

Historique de l'issue : https://github.com/tchapgouv/tchap-infra/pull/2608

**Comment by MatMaul** [comment]
2 pbs ici : on devrait avoir l'avatar pour la room aussi et pas que le user, j'ai oublié une config.
La room ne devrait pas être encrypté mais ca je sais pas trop pourquoi c'est sensé être corrigé depuis https://github.com/matrix-org/synapse/pull/16677

**Comment by MatMaul** [comment]
![image](https://github.com/tchapgouv/tchap-backend/assets/1643573/024f2147-55a3-4746-b46e-8837c41464a5)

C'est mieux :)

J'ai un bug dans ma PR upstream cependant :/

**Comment by MatMaul** [comment]
https://github.com/element-hq/synapse/pull/17033 :sob:

**Comment by mcalinghee** [comment]
bug non bloquant pour la release 1.103
