### ISSUE TITLE
Upgrade Synapse 1.103 - Bug d'invitation externe

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-backend#30]
- [ ] EDIT : j'ai recu le mail d'invitation d'externe avec quelues minutes de délai sur ma boite gmail. Le template n'est pas bon, lorsque je clique sur "rejoindre Tchap" je tombe sur la landing page

![image](https://github.com/tchapgouv/tchap-infra/assets/4077729/6dbf5496-7271-4cfb-887c-94b4cac9e863)

**Comment by odelcroi** [comment]
Ticket lié : https://github.com/tchapgouv/tchap-infra/issues/2616

**Comment by mcalinghee** [comment]
for info : issue is here https://github.com/tchapgouv/tchap-infra/issues/2621
