### ISSUE TITLE
Upgrade Synapse 1.103 - Envoi message a travers Rageshake

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-backend#31]
- [ ] error 404 lors de : TMG_19_1	externe	envoyer un message au support à travers rageshake

![image](https://github.com/tchapgouv/tchap-infra/assets/4077729/63efc5ea-40b4-485e-9785-9660042059eb)

**Comment by odelcroi** [comment]
Ca pourrait etre qu'il n'y a pas de serveur rageshake en DEV :D

**Comment by mcalinghee** [comment]
> Ca pourrait etre qu'il n'y a pas de serveur rageshake en DEV :D

a valider en preprod?

**Comment by MatMaul** [comment]
Le rageshake server est bien là. Je viens d'envoyer des logs sans soucis ?

**Comment by MatMaul** [comment]
on a bien recu mon rageshake et celui de NicOS. Je pense qu'on peut clore.
