### ISSUE TITLE
Fix rooms power levels for DMs and live location sharing

### ISSUE THREAD

**Issue by MatMaul** [tchapgouv/tchap-backend#38]
One bug was introduced probably during the mainlining: DMs don't have both of their members admin like it should be the case.
Fixed by https://github.com/tchapgouv/synapse-room-access-rules/pull/2.

Also live location sharing is using state events, which are not allowed by default for normal users in a typical room.
Fixed by https://github.com/tchapgouv/synapse-room-access-rules/pull/3.

Both of those fixes are for rooms created after applying the fixes.

For existing rooms, https://github.com/tchapgouv/synapse-room-access-rules/pull/4 should fix them.

**Comment by MatMaul** [comment]
Currently the script to fix existing DMs uses the event `im.vector.room.access_rules` to check if it is a DM.

Old rooms don't have this event, but it seems the bug and this event came together with the mainlining deploy => it should be fine to use it to fix problematic DMs. I am however still not sure of this.

**Comment by MatMaul** [comment]
Script has been run successfully on dev and preprod.

It failed on a specific room on DINUM, I am looking into why.

From the data gathered on the DINUM run, it seems to handle about 20k rooms per hour.

There is 390k rooms on interieur and 290k on finances, so it should not take longer than a day.

**Comment by odelcroi** [comment]
On Tchap Web, the script happens to notify users of the room power level change which is surprising.

This doe snot happen on Tchap Android, nor Tchap iOs

For instance in a DM : 

![image](https://github.com/tchapgouv/tchap-backend/assets/4077729/175cea70-fa28-4349-8f9c-c4699dbc5c5f)

**Comment by mcalinghee** [comment]
> this script can be split in two :
> 
> * DM ->
> * live location sharing

Fixed by : 
https://github.com/tchapgouv/synapse-room-access-rules/pull/5
https://github.com/tchapgouv/tchap-infra/pull/2742
